{% set data = load_setup_py_data() %}
package:
  name: mmd
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - python
    - numpy x.x
    - scipy >=0.16
    - cython
    - gcc [osx]
  run:
    - python
    - numpy x.x
    - scipy >=0.16
    - libgcc [osx]

test:
  imports:
    - mmd

about:
  home: https://github.com/dougalsutherland/mmd
  license: BSD-3
  license_file: LICENSE
  summary: Some utilities for dealing with the maximum mean discrepancy (MMD) and related tools
